package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// cmdProviderScaffold generates a new provider skeleton.
// Usage: sir provider scaffold --name <name> --kind <kind> [--lang python|go] [--dir <dir>]
func cmdProviderScaffold(args []string) {
	name := ""
	kind := "signal_provider"
	lang := "python"
	dir := "examples/providers"

	for i, a := range args {
		switch a {
		case "--name":
			if i+1 < len(args) {
				name = args[i+1]
			}
		case "--kind":
			if i+1 < len(args) {
				kind = args[i+1]
			}
		case "--lang":
			if i+1 < len(args) {
				lang = args[i+1]
			}
		case "--dir":
			if i+1 < len(args) {
				dir = args[i+1]
			}
		}
	}

	if name == "" {
		fmt.Fprintf(os.Stderr, "usage: sir provider scaffold --name <name> [--kind signal_provider|effect_provider|policy_provider|advisory_provider|export_provider] [--lang python|go] [--dir dir]\n")
		os.Exit(1)
	}

	providerDir := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Join(providerDir, "fixtures"), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	// Write provider manifest
	manifestContent := scaffoldManifest(name, kind, lang)
	if err := os.WriteFile(filepath.Join(providerDir, "provider.yaml"), []byte(manifestContent), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing manifest: %v\n", err)
		os.Exit(1)
	}

	// Write provider implementation
	var implPath string
	var implContent string
	switch lang {
	case "go":
		implPath = filepath.Join(providerDir, "provider.go")
		implContent = scaffoldGo(name, kind)
	default:
		implPath = filepath.Join(providerDir, "provider.py")
		implContent = scaffoldPython(name, kind)
		_ = os.Chmod(implPath, 0o755)
	}

	if err := os.WriteFile(implPath, []byte(implContent), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "error writing implementation: %v\n", err)
		os.Exit(1)
	}

	// Write example fixture
	fixturePath := filepath.Join(providerDir, "fixtures", "example.json")
	if err := os.WriteFile(fixturePath, []byte(scaffoldFixture(kind)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing fixture: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("scaffolded provider: %s\n", providerDir)
	fmt.Printf("  manifest:    provider.yaml\n")
	fmt.Printf("  entrypoint:  %s\n", filepath.Base(implPath))
	fmt.Printf("  fixture:     fixtures/example.json\n")
	fmt.Println()
	fmt.Printf("Next steps:\n")
	fmt.Printf("  1. Implement the logic in %s\n", filepath.Base(implPath))
	fmt.Printf("  2. Add real fixture cases to fixtures/\n")
	fmt.Printf("  3. sir provider validate %s/provider.yaml\n", providerDir)
	fmt.Printf("  4. sir provider test %s/provider.yaml\n", providerDir)
}

func scaffoldManifest(name, kind, lang string) string {
	ep := "./provider.py"
	if lang == "go" {
		ep = "./" + name
	}
	caps := "  # TODO: declare actual capabilities"
	switch kind {
	case "signal_provider":
		caps = "  signal_reliability: [declared_intent]\n  timing: [pre_exec]"
	case "effect_provider":
		caps = "  record: true\n  contain: false"
	case "policy_provider":
		caps = "  verdict_types: [allow, ask, deny]\n  is_advisory: true"
	case "advisory_provider":
		caps = "  risk_levels: [low, medium, high]\n  is_advisory: true"
	case "export_provider":
		caps = "  export: true\n  format: jsonl"
	}
	return fmt.Sprintf(`schema_version: sir.provider.v0
name: %s
kind: %s
version: 0.1.0
protocol: stdio-json
entrypoint: %s
platforms: [macos, linux, windows]
capabilities:
%s
fixtures:
  - fixtures/example.json
`, name, kind, ep, caps)
}

func scaffoldPython(name, kind string) string {
	var body string
	switch kind {
	case "effect_provider":
		body = `
def handle_effect(req):
    effect_type = req.get("type", "")
    effect_id = req.get("effect_id", "")
    # TODO: implement effect handling
    return sir_sdk.effect_unavailable(effect_id, f"not implemented: {effect_type}")


sir_sdk.run_effect_provider(caps, handle_effect)`
	default:
		body = `
def emit(event: dict):
    # TODO: convert native event to sir.signal.v0
    return sir_sdk.make_signal(
        signal_id=event.get("signal_id", "sig-001"),
        signal_time=event.get("signal_time", "1970-01-01T00:00:00Z"),
        source_kind="` + strings.ReplaceAll(name, "-", "_") + `",
        reliability=sir_sdk.RELIABILITY_DECLARED_INTENT,
        timing=sir_sdk.TIMING_PRE_EXEC,
        action_claim=event.get("action_claim", {"type": "unknown"}),
        provider_name=PROVIDER_NAME,
        provider_version=PROVIDER_VERSION,
    )


sir_sdk.run_signal_provider(caps, emit)`
	}

	return fmt.Sprintf(`#!/usr/bin/env python3
"""
%s provider — generated by sir provider scaffold.
Replace this stub with real implementation.
"""
import sir_sdk

PROVIDER_NAME = %q
PROVIDER_VERSION = "0.1.0"


def caps():
    return sir_sdk.capabilities(
        PROVIDER_NAME,
        sir_sdk.KIND_%s,
        {},  # TODO: declare actual capabilities
    )

%s
`, name, name, strings.ToUpper(strings.TrimSuffix(kind, "_provider")), body)
}

func scaffoldGo(name, kind string) string {
	return fmt.Sprintf(`package main

// %s provider — generated by sir provider scaffold.
// Replace this stub with real implementation.

import (
	"github.com/somoore/sir/pkg/sdk"
)

func main() {
	sdk.RunSignalProvider(
		func() sdk.CapabilitiesResponse {
			return sdk.NewCapabilitiesResponse(%q, sdk.Kind%s, map[string]any{
				// TODO: declare actual capabilities
			})
		},
		func(event map[string]any) *sdk.Signal {
			// TODO: convert event to sdk.Signal
			return nil
		},
	)
}
`, name, name, kindConst(kind))
}

func kindConst(kind string) string {
	switch kind {
	case "signal_provider":
		return "SignalProvider"
	case "effect_provider":
		return "EffectProvider"
	case "policy_provider":
		return "PolicyProvider"
	case "advisory_provider":
		return "AdvisoryProvider"
	case "export_provider":
		return "ExportProvider"
	}
	return "SignalProvider"
}

func scaffoldFixture(kind string) string {
	switch kind {
	case "effect_provider":
		return `{
  "schema_version": "sir.effect_request.v0",
  "effect_id": "eff_example_001",
  "type": "record",
  "required": true,
  "fail_closed": false,
  "target": {"kind": "process", "pid": 1234}
}
`
	default:
		return `{
  "signal_id": "example-001",
  "signal_time": "2026-01-01T00:00:00Z",
  "action_claim": {"type": "shell_exec", "target": {"display": "echo hello", "sensitivity": "low"}}
}
`
	}
}
